### PR TITLE
Correctly call __tgt_target_teams if there is any teams construct inside target

### LINKED ISSUE #22: split target teams spawns only 1 team per default
```C
#include <stdlib.h>
#include <stdio.h>

#include <omp.h>

int main(int argc, char* argv[])
{
	#pragma omp target
	#pragma omp teams
	{
		printf("split target and teams: %d team(s)\n", omp_get_num_teams());
	}

	#pragma omp target teams
	{
		printf("combined target teams:  %d team(s)\n", omp_get_num_teams());
	}

	return EXIT_SUCCESS;
}
```

Output:
```
split target and teams: 1 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
combined target teams:  14 team(s)
```

### PR DESCRIPTION
**Pull request by hahnjo**
Fixes #22

### CODE REVIEW

**Comment by carlobertolli** [comment]
Hi hahnjo

Thanks for finding this out and proposing a solution. A quick question: why do you need to save the num_teams and thread_limit expressions on the OpenMP stack? I am asking because target and teams cannot be nested between themselves (no target inside target, no more than one teams inside target). Can you not just save them in local function variables and then re-use them later on?

Thanks!

-- Carlo

**Comment by hahnjo** [comment]
Hi Carlo,

I think I haven't changed anything with this, have I?

From my understanding what happens is:
 * create a new (temporary) OpenMP region
 * parse the teams construct in `EmitOMPDirectiveWithTeams` (without target)
 * and get the information from the stack prior to ending the region

This could be done with local variables as well but possibly with code duplication? @sfantao 

Greetings,
Jonas

**Comment by carlobertolli** [comment]
Hi

No you have not - I have not tried this yet, only looked at the code.
Looking more carefully, I now see the issue. The problem in the uncombined case is that we enter EmitOMPDirectiveWithTeams and we do not record num_teams and thread_limit info but we try to extract it later on from the target construct.

You are also right: we cannot use local variables because the info it is in two different functions. Using the OMP stack looks fine.

Let me give this a run on our local repo and I will let you know.

Thanks!

-- Carlo

**Comment by carlobertolli** [comment]
Hi

I found out that when we only have target, then teams will be automatically activated and tgt_target_teams will be called, instead of just tgt_target. One solution is to add the following:

    CGM.OpenMPSupport.setTeams(false);

at line 2287 of CGStmtOpenMP.cpp.

Can you try this out please?

Thanks!

-- Carlo

**Comment by hahnjo** [comment]
Hi,

while I'm not strongly against this (should work from code, but haven't tested) I think this should not be necessary: The other attributes are also often not set to `false` and they are also working correctly.

In a short test case clang generated a call to `__tgt_target` for a plain target. Could you share the code you are seeing the wrong call with? Maybe you are hitting a corner case that I haven't thought of...

Greetings
Jonas

**Comment by carlobertolli** [comment]
Hi

The point is, I think, that the "teams" field is initialized to true by default. If we only see target, without teams, then we should reset it to false until we possibly see a teams.

The example:

#include <stdlib.h>
#include <stdio.h>

#define N 64

int main ()
{
  int i;
  int a[N], a_h[N];
  int b[N];

  for (i = 0 ; i < N ; i++)
  {
    a[i] = a_h[i] = -1;
    b[i] = i;
  }

#pragma omp target map(tofrom:a,b)
  {
#pragma omp parallel for schedule(static)
    for (i = 0 ; i < N ; i++)
    {
      a[i] += b[i];
    }
  }

  for (i = 0 ; i < N ; i++)
  {
    a_h[i] += b[i];
  }

  int resAreFine = 0;
  for (i = 0 ; i < N ; i++)
    if (a[i] != a_h[i])
    {
      printf ("%d: a_h = %d, a = %d\n", i, a_h[i], a[i]);
      resAreFine = 1;
    }
  if (resAreFine == 0)
    printf ("Results are fine\n");
}

-- Carlo

**Comment by hahnjo** [comment]
Hi Carlo,

could you wrap your code into a paragraph? Some of the includes are gone...
(https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks)

Thanks!
Jonas

**Comment by carlobertolli** [comment]
Ups - let me try:

```
#include <stdlib.h>
#include <stdio.h>

#define N 64

int main ()
{
  int i;
  int a[N], a_h[N];
  int b[N];

  int n = N;

  check_offloading();

  for (i = 0 ; i < N ; i++)
  {
    a[i] = a_h[i] = -1;
    b[i] = i;
  }

#pragma omp target map(tofrom:a,b)
  {
#pragma omp parallel for schedule(static)
    for (i = 0 ; i < n ; i++)
    {
      a[i] += b[i];
    }
  }

  for (i = 0 ; i < N ; i++)
  {
    a_h[i] += b[i];
  }

  int resAreFine = 0;
  for (i = 0 ; i < N ; i++)
    if (a[i] != a_h[i])
    {
      printf ("%d: a_h = %d, a = %d\n", i, a_h[i], a[i]);
      resAreFine = 1;
    }
  if (resAreFine == 0)
    printf ("Results are fine\n");
}
```

-- Carlo

**Comment by carlobertolli** [comment]
Ah! I left a missing function call in:

```
#include <stdlib.h>
#include <stdio.h>

#define N 64

int main ()
{
  int i;
  int a[N], a_h[N];
  int b[N];

  int n = N;

  for (i = 0 ; i < N ; i++)
  {
    a[i] = a_h[i] = -1;
    b[i] = i;
  }

#pragma omp target map(tofrom:a,b)
  {
#pragma omp parallel for schedule(static)
    for (i = 0 ; i < n ; i++)
    {
      a[i] += b[i];
    }
  }

  for (i = 0 ; i < N ; i++)
  {
    a_h[i] += b[i];
  }

  int resAreFine = 0;
  for (i = 0 ; i < N ; i++)
    if (a[i] != a_h[i])
    {
      printf ("%d: a_h = %d, a = %d\n", i, a_h[i], a[i]);
      resAreFine = 1;
    }
  if (resAreFine == 0)
    printf ("Results are fine\n");
}
```

Sorry!

-- Carlo

**Comment by hahnjo** [comment]
Thanks for the code!

Very interesting: The error doesn't trigger with your code but now my test case shows the bad behaviour it hasn't yesterday and in the morning...

I will insert the call to `setTeams(false)` as suggested and see whether this kind of error might be true for the other variables on the stack as well.

Cheers,
Jonas

**Comment by carlobertolli** [comment]
Hi

I may have been unclear about this test. It actually returns incorrect results. What happens is that we generate a call to tgt_target_teams instead of simply tgt_target. As multiple teams are started, but no distribute is used, all teams execute redundantly the innermost for-loop. As the loop is a +=, then we can detect incorrect results.

Thanks!

-- Carlo

**Comment by hahnjo** [comment]
Yep, I understood the intention. But it doesn't always happen, it's an unitialized value that isn't predictible. That's why my test case has worked until now...

Currently compiling with the added line...

Jonas

**Comment by hahnjo** [comment]
I've updated the commit, working correctly as far as I can tell.

The other variables are partly also uninitialized but this isn't noticed because they aren't used. Maybe they be cleaned up (Distribute for example)

**Comment by carlobertolli** [comment]
This is passing all my local regression tests. I think it is good to accept the pull request.

Thanks again for your effort in finding and fixing the issue!

-- Carlo

**Pull request merged**
